# Generated by Django 2.2.6 on 2020-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='age',
        ),
        migrations.RemoveField(
            model_name='room',
            name='buildingStructure',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default='京都市左京区吉田本町', max_length=255, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='age',
            field=models.IntegerField(default=12, verbose_name='築年数'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='appearance',
            field=models.CharField(default='https://image2.homes.jp/smallimg/image.php?file=http%3A%2F%2Fimage.homes.renters.jp%2F51bc6a50-5ad1-411e-b30e-b4643a59643c_property_picture_2347_large.jpg', max_length=2048, verbose_name='外観画像URL'),
        ),
    ]
