# Generated by Django 2.2.6 on 2020-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20201125_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='areBathAndToiletSeparated',
            field=models.BooleanField(verbose_name='バストイレが分かれているか'),
        ),
    ]
