# Generated by Django 2.2.6 on 2020-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20201129_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='areBathAndToiletSeparated',
            field=models.BooleanField(verbose_name='バストイレが分かれている'),
        ),
    ]
