# Generated by Django 2.2.6 on 2020-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_auto_20201129_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floorImage',
            field=models.CharField(default='https://image3.homes.jp/smallimg/image.php?file=http%3A%2F%2Fimg.homes.jp%2Fv4ai88hj3p84kjp.jpg ', max_length=2048, verbose_name='間取り画像'),
        ),
    ]
